# SPDX-FileCopyrightText: 2025 Łukasz Niemier <#@hauleth.dev>
#
# SPDX-License-Identifier: Apache-2.0
---
scope/tests:
- changed-files:
  - any-glob-to-any-file: ['test/*']

scope/ci:
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/*']
